name: CI

on:
  push:
    branches: [ master ]

env:
  BUCKET: 'gobarbergcs.arthurgrigoletto.dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: yarn install
      
    # - name: Run tests
    #  run: yarn test --watchAll false
      
    - name: Build
      run: yarn build
      

